export const allFonts = [
    {
        name: "Original",
    },

    /*********************************************** TEMPLATE ***********************************************
    {
        name: "xxxxxxxxxxxx",
        openingCharacterWrapper: "xxxxxxxxxxxx",
        closingCharacterWrapper: "xxxxxxxxxxxx",
        openingTextWrapper: "xxxxxxxxxxxx",
        closingTextWrapper: "xxxxxxxxxxxx",
        characters: {
            'a': 'a',
            'b': 'b',
            'c': 'c',
            'd': 'd',
            'e': 'e',
            'f': 'f',
            'g': 'g',
            'h': 'h',
            'i': 'i',
            'j': 'j',
            'k': 'k',
            'l': 'l',
            'm': 'm',
            'n': 'n',
            'o': 'o',
            'p': 'p',
            'q': 'q',
            'r': 'r',
            's': 's',
            't': 't',
            'u': 'u',
            'v': 'v',
            'w': 'w',
            'x': 'x',
            'y': 'y',
            'z': 'z',
            'A': 'A',
            'B': 'B',
            'C': 'C',
            'D': 'D',
            'E': 'E',
            'F': 'F',
            'G': 'G',
            'H': 'H',
            'I': 'I',
            'J': 'J',
            'K': 'K',
            'L': 'L',
            'M': 'M',
            'N': 'N',
            'O': 'O',
            'P': 'P',
            'Q': 'Q',
            'R': 'R',
            'S': 'S',
            'T': 'T',
            'U': 'U',
            'V': 'V',
            'W': 'W',
            'X': 'X',
            'Y': 'Y',
            'Z': 'Z',
        }
    },
    *********************************************** TEMPLATE ***********************************************/

    {
        name: "Smiley Face Text Wrapper",
        openingTextWrapper: "☺",
        closingTextWrapper: "☺",
    },
    {
        name: "Smiley Face Character Wrapper",
        openingCharacterWrapper: "☺",
        closingCharacterWrapper: "☺",
    },
    {
        name: "Parentheses Character Wrapper",
        openingCharacterWrapper: "(",
        closingCharacterWrapper: ")"
    },
    {
        name: "Dice Character Wrapper",
        openingCharacterWrapper: "⚀",
        closingCharacterWrapper: "⚅"
    },
    {
        name: "Handwriting 6 Dice Text Wrapper",
        openingTextWrapper: "⚀ ⚁ ⚂ ⚃ ⚄ ⚅ ",
        closingTextWrapper: " ⚅ ⚄ ⚃ ⚂ ⚁ ⚀",
        characters: {
            'a': '𝒶',
            'b': '𝒷',
            'c': '𝒸',
            'd': '𝒹',
            'e': '𝑒',
            'f': '𝒻',
            'g': '𝑔',
            'h': '𝒽',
            'i': '𝒾',
            'j': '𝒿',
            'k': '𝓀',
            'l': '𝓁',
            'm': '𝓂',
            'n': '𝓃',
            'o': '𝑜',
            'p': '𝓅',
            'q': '𝓆',
            'r': '𝓇',
            's': '𝓈',
            't': '𝓉',
            'u': '𝓊',
            'v': '𝓋',
            'w': '𝓌',
            'x': '𝓍',
            'y': '𝓎',
            'z': '𝓏',
            'A': '𝒜',
            'B': 'ℬ',
            'C': '𝒞',
            'D': '𝒟',
            'E': 'ℰ',
            'F': 'ℱ',
            'G': '𝒢',
            'H': 'ℋ',
            'I': 'ℐ',
            'J': '𝒥',
            'K': '𝒦',
            'L': 'ℒ',
            'M': 'ℳ',
            'N': '𝒩',
            'O': '𝒪',
            'P': '𝒫',
            'Q': '𝒬',
            'R': 'ℛ',
            'S': '𝒮',
            'T': '𝒯',
            'U': '𝒰',
            'V': '𝒱',
            'W': '𝒲',
            'X': '𝒳',
            'Y': '𝒴',
            'Z': '𝒵',
        }
    },
    {
        name: "6 Dice",
        openingTextWrapper: "⚀ ⚁ ⚂ ⚃ ⚄ ⚅ ",
        closingTextWrapper: " ⚅ ⚄ ⚃ ⚂ ⚁ ⚀"
    },
    {
        name: "Handwriting",
        characters: {
            'a': '𝒶',
            'b': '𝒷',
            'c': '𝒸',
            'd': '𝒹',
            'e': '𝑒',
            'f': '𝒻',
            'g': '𝑔',
            'h': '𝒽',
            'i': '𝒾',
            'j': '𝒿',
            'k': '𝓀',
            'l': '𝓁',
            'm': '𝓂',
            'n': '𝓃',
            'o': '𝑜',
            'p': '𝓅',
            'q': '𝓆',
            'r': '𝓇',
            's': '𝓈',
            't': '𝓉',
            'u': '𝓊',
            'v': '𝓋',
            'w': '𝓌',
            'x': '𝓍',
            'y': '𝓎',
            'z': '𝓏',
            'A': '𝒜',
            'B': 'ℬ',
            'C': '𝒞',
            'D': '𝒟',
            'E': 'ℰ',
            'F': 'ℱ',
            'G': '𝒢',
            'H': 'ℋ',
            'I': 'ℐ',
            'J': '𝒥',
            'K': '𝒦',
            'L': 'ℒ',
            'M': 'ℳ',
            'N': '𝒩',
            'O': '𝒪',
            'P': '𝒫',
            'Q': '𝒬',
            'R': 'ℛ',
            'S': '𝒮',
            'T': '𝒯',
            'U': '𝒰',
            'V': '𝒱',
            'W': '𝒲',
            'X': '𝒳',
            'Y': '𝒴',
            'Z': '𝒵',
        }
    }
];